In [13]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a1=np.array([[7,8,9],[10,11,12]])
print(a)
print(a1)

#concatinating two arrays
a_new=np.concatenate((a,a1),axis=1)
print("\nconcateinating two arr:\n",a_new)

#revers of an array
res=np.flip(a)
print("\nreves of a:\n",res)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

concateinating two arr:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

reves of a:
 [[6 5 4]
 [3 2 1]]
